[tool.ruff]
line-length = 120
target-version = "py311"
select = ["E", "F", "W", "I", "B"]
ignore = ["E501"]

[tool.ruff.isort]
known-first-party = ["backend"]
combine-as-imports = true

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning:sqlite3.*:",
    "ignore:The default datetime adapter is deprecated:DeprecationWarning",
    "ignore:datetime.datetime.utcnow:DeprecationWarning",
    "ignore::PendingDeprecationWarning",
]

